Added odds percentage for each sport and logging game label
thales-markets/overtimemarkets-bots pull request #2
Opened 2022-07-27 12:56 UTC by grujawork

2022-07-28 12:26 UTC, danijelthales requested changes

2022-07-28 12:26 UTC, danijelthales commented on source/pullOdds/pullOdds.js
> +    2: process.env.ODDS_PERCENTAGE_CHANGE_NFL,
I would use a default value, and have overrides per sport. Better than having to specify 15 values.

2022-07-28 18:08 UTC, grujawork commented on source/pullOdds/pullOdds.js
> +    2: process.env.ODDS_PERCENTAGE_CHANGE_NFL,
but then each time will need to deploy a new bot when we want to add something to it. with this, it would be ok if we want to change some parameters. and also we bring logic inside the bot or do you mean for example:
```
const ODDS_PERCENTAGE_CHANGE_BY_SPORT = {
    2: process.env.ODDS_PERCENTAGE_CHANGE_DEFAULT,
    3: process.env.ODDS_PERCENTAGE_CHANGE_MLB,
    4: process.env.ODDS_PERCENTAGE_CHANGE_DEFAULT,
    6: process.env.ODDS_PERCENTAGE_CHANGE_DEFAULT,
    7: process.env.ODDS_PERCENTAGE_CHANGE_DEFAULT,
    10: process.env.ODDS_PERCENTAGE_CHANGE_DEFAULT,
    11: process.env.ODDS_PERCENTAGE_CHANGE_EPL,
    12: process.env.ODDS_PERCENTAGE_CHANGE_DEFAULT,
    13: process.env.ODDS_PERCENTAGE_CHANGE_DEFAULT,
    14: process.env.ODDS_PERCENTAGE_CHANGE_DEFAULT,
    15: process.env.ODDS_PERCENTAGE_CHANGE_DEFAULT,
    16: process.env.ODDS_PERCENTAGE_CHANGE_DEFAULT,
  };
  ```

2022-07-28 18:10 UTC, grujawork commented on source/pullOdds/pullOdds.js
> +    2: process.env.ODDS_PERCENTAGE_CHANGE_NFL,
or you mean 

```
const ODDS_PERCENTAGE_CHANGE_BY_SPORT = {
    3: process.env.ODDS_PERCENTAGE_CHANGE_MLB,
    11: process.env.ODDS_PERCENTAGE_CHANGE_EPL,
  };
  ```
  and if not exist in the map use `process.env.ODDS_PERCENTAGE_CHANGE_DEFAULT`

2022-08-01 09:37 UTC, danijelthales commented on source/pullOdds/pullOdds.js
> +    2: process.env.ODDS_PERCENTAGE_CHANGE_NFL,
yes, that

2022-08-01 10:10 UTC, grujawork commented on source/pullOdds/pullOdds.js
> +    2: process.env.ODDS_PERCENTAGE_CHANGE_NFL,
done

2022-08-01 10:59 UTC, merged